### ISSUE TITLE
App configuration persistence

### ISSUE THREAD

**Issue by mbwilding** [markusdd/affinity-linux-distrobox#1]
Hey mate,

I run arch natively so I did this without the distrobox part. I am having an issue with persistence, have you found that? As in none of the changed settings stick around on next load.

Thanks for throwing this together.

**Comment by markusdd** [comment]
Hi!

You might wanna check the affinity forum link I have in the README.

There it is explained that this currently is unsolved, so this is not something about this setup in particular.

Unfortunately someone will first have to dig into that to find out what library piece is missing.
